# Generated by Django 4.0.4 on 2022-04-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('status', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='')),
                ('demo_link', models.CharField(max_length=250, null=True)),
                ('source_code', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
